name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog_project

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: jp
          MYSQL_DATABASE: blog_db
          MYSQL_USER: coursera
          MYSQL_PASSWORD: jp
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Create Virtual Environment
      run: |
        python -m venv myenv
        source myenv/bin/activate
    
    - name: Install Dependencies
      run: |
        source myenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Django Tests
      env:
        DJANGO_SETTINGS_MODULE: blog_project.settings
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 3306
        MYSQL_USER: coursera
        MYSQL_PASSWORD: jp
        MYSQL_ROOT_PASSWORD: jp
        MYSQL_DATABASE: blog_db
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
      run: |
        source myenv/bin/activate
        python manage.py check
        python manage.py test
