name: EC2 Disk Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Cleanup Disk Space
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: 3.83.99.159
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} "
            echo 'Current disk space usage:'
            df -h
            echo -e '\nCurrent Docker space usage:'
            sudo docker system df
            echo -e '\nCleaning up Docker system...'
            sudo docker system prune -af
            sudo docker image prune -af
            echo -e '\nFinal disk space usage:'
            df -h
            echo -e '\nFinal Docker space usage:'
            sudo docker system df
          "
          rm -f private_key
