name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: jp
          MYSQL_DATABASE: blog_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Create Virtual Environment
      run: |
        cd blog_project
        python -m venv myenv
        source myenv/bin/activate
    
    - name: Install Dependencies
      run: |
        cd blog_project
        source myenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt
    
    - name: Run Django Tests
      env:
        DJANGO_SETTINGS_MODULE: blog_project.settings
        DATABASE_HOST: coursera-mysql-instance.csbkk0sq0j1o.us-east-1.rds.amazonaws.com
        DATABASE_PORT: 3306
        MYSQL_USER: coursera
        MYSQL_PASSWORD: coursera
      run: |
        cd blog_project
        source myenv/bin/activate
        python manage.py check
        python manage.py test
