name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: jp
          MYSQL_DATABASE: blog_db
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3307:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          #python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: Run Django checks
        #run: |
          #python3 blog_project/manage.py check


      # This creates a .env file with your secrets
      - name: Create .env file
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}" >> .env
          echo "DB_NAME=blog_db" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASSWORD=jp" >> .env
          echo "DB_HOST=127.0.0.1" >> .env

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: blog_project.settings
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
          DB_NAME: blog_db
          DB_USER: root
          DB_PASSWORD: jp
          DB_HOST: 127.0.0.1
        run: |
          python3 blog_project/manage.py test blog
